# Generated by Django 4.2.13 on 2024-06-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumeApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InputForm",
        ),
    ]
